project:
  type: website
  output-dir: docs

website:
  title: "Jeb Dee"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Projects.qmd
        text: Projects
      - href: Activities.qmd
        text: Activities

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false